__root_path = '/home/itaas/AI-Lab'
EMBEDDING_FILE = "{}/dianping_w2v_kv.vec".format(__root_path)
TRAIN_PATH = "{}/rating_train.csv".format(__root_path)
TEST_PATH = "{}/validation_binary.csv".format(__root_path)

Y = "location_traffic_convenience_unrelated location_traffic_convenience_positive location_traffic_convenience_neutral location_traffic_convenience_neg location_distance_from_business_district_unrelated " \
    "location_distance_from_business_district_positive location_distance_from_business_district_neutral location_distance_from_business_district_neg " \
    "location_easy_to_find_unrelated location_easy_to_find_positive location_easy_to_find_neutral location_easy_to_find_neg service_wait_time_unrelated service_wait_time_positive service_wait_time_neutral service_wait_time_neg service_waiters_attitude_unrelated service_waiters_attitude_positive service_waiters_attitude_neutral service_waiters_attitude_neg " \
    "service_parking_convenience_unrelated service_parking_convenience_positive service_parking_convenience_neutral service_parking_convenience_neg service_serving_speed_unrelated service_serving_speed_positive service_serving_speed_neutral service_serving_speed_neg price_level_unrelated price_level_positive " \
    "price_level_neutral price_level_neg price_cost_effective_unrelated price_cost_effective_positive price_cost_effective_neutral price_cost_effective_neg " \
    "price_discount_unrelated price_discount_positive price_discount_neutral price_discount_neg environment_decoration_unrelated environment_decoration_positive environment_decoration_neutral " \
    "environment_decoration_neg environment_noise_unrelated environment_noise_positive environment_noise_neutral environment_noise_neg environment_space_unrelated environment_space_positive environment_space_neutral " \
    "environment_space_neg environment_cleaness_unrelated environment_cleaness_positive environment_cleaness_neutral environment_cleaness_neg dish_portion_unrelated dish_portion_positive dish_portion_neutral dish_portion_neg dish_taste_unrelated dish_taste_positive dish_taste_neutral dish_taste_neg dish_look_unrelated dish_look_positive dish_look_neutral dish_look_neg dish_recommendation_unrelated dish_recommendation_positive dish_recommendation_neutral dish_recommendation_neg others_overall_experience_unrelated others_overall_experience_positive others_overall_experience_neutral others_overall_experience_neg others_willing_to_consume_again_unrelated others_willing_to_consume_again_positive others_willing_to_consume_again_neutral others_willing_to_consume_again_neg".split()

X = 'comment'
MAX_LEN = 200
EMBED_SIZE = 100

TOKENIZER_NAME = 'model/tokenizer-0831-2.tk'
MODEL_NAME = 'model/rating_classification_2018_0831-2.h5'
